### ISSUE TITLE
startRegion "upstream" not working

### ISSUE THREAD

**Issue by Miswi** [Roleren/ORFik#95] opened 2020-06-25 14:35 UTC
startRegion functions behaves as if "upstream" option is set to "0" for any positive number (getting any upstream region with startRegion function is impossible).
It's caused by constraints put on relative start position calculation in windowPerGroup function (original code commented with #):

windowPerGroup <- function(gr, tx, upstream = 0L, downstream = 0L) {
  g <- asTX(gr, tx)
  indices <- chmatch(txNames(gr), names(tx))
  
  txEnds <- widthPerGroup(tx[indices], FALSE)
  #starts <- pmin(pmax(start(g) - upstream, 1L), txEnds)
  starts <- start(g) - upstream ## constraints removed
  if (downstream != 0L) {
     # ends <- pmin(pmax(end(g) + downstream, starts - 1),
     #              widthPerGroup(tx[indices], FALSE))
    ends <- end(g) + downstream ## constraints removed - doesn't work because of pmapFromTranscriptsCPP
    ranges(g) <- IRanges(starts, ends) 
  } else {
    start(g) <- starts
  }
  g <- ranges(g)
  names(g) <- indices
  region <- pmapFromTranscriptF(g, tx, TRUE)
  names(region) <- names(gr)
  return(region)
}

After removing the constraints (commented with ##) the function behaves as expected.
It doesn't work likewise for downstream > widthPerGroup(tx[indices], FALSE) - pmapFromTranscriptsCPP crashes R then. It's somewhat strange to me - it seems that getting region downstream of stop codon is a useful feature to have too. 

check width(startRegion(grl)); with default options it always gives 3, but documentation states it should be 5; my fix seems to resolve it, with the exception for a warning at the ranges(g) <- IRanges(starts,ends) line.

**Comment by Roleren** [comment] 2020-06-25 21:01
Thanks, working on it now, will update it by tomorrow and let you know.

**Comment by Roleren** [comment] 2020-06-25 21:20
Hm, not reproducing the error here, this is test for me.

I put the answers to the tests as comment, do you get the same ranges back ?

```
library(ORFik)
gr.tx <- GRanges("1", IRanges(1, width = 100), "+")
gr.grl <- GRanges("1", IRanges(50, width = 25), "+")
grl <- split(gr.grl, seq_along(length(gr.grl)))
tx <- split(gr.tx, seq_along(length(gr.tx)))
# tests
startRegion(grl, tx) # <- IRanges: 48-52
startRegion(grl, tx, upstream = 40, downstream = 27) # <- IRanges: 10-77
startRegion(grl, tx, downstream = 27) # <- IRanges: 48-77
```

**Comment by Miswi** [comment] 2020-06-26 15:54
Thanks for answer,

I wasn't using the newest version of ORFik, good point. 
The misunderstanding was that I referred to a situation where

startRegion(grl, tx=null), 
to extend the leader, I see now that there are extendLeaders and extendTrailers functions which work perfectly for adding pseudoutrs. I had a situation in mind where you can access any arbitrary location referred to annotation (exon structure), a wrapper for that would be:

transformRegions <- function(grl, upstream = 2L, downstream = 2L, fix = c("start", "end")[1], is.sorted = TRUE ) {
  if (fix == "start") {
    tx <- extendLeaders(grl, pmax(upstream,0)) 
    downstream_extensions <- downstream - widthPerGroup(grl) 
    tx <- extendTrailers(tx, pmax(downstream_extensions,0))
    result <- startRegion(grl=grl,tx=tx,upstream=Inf,downstream=downstream, is.sorted = is.sorted)
  }
  if (fix == "end") {
    upstream_extensions <- upstream - widthPerGroup(grl)
    tx <- extendLeaders(grl, pmax(upstream_extensions, 0))
    tx <- extendTrailers(grl, pmax(downstream, 0))
    result <- stopRegion(grl=grl,tx=tx,upstream=upstream, downstream = Inf, is.sorted = is.sorted)
  }
  return(result)
}
where stopRegion is simply based on startRegion, but with stopSites instead of startSites:

stopRegion <- function(grl, tx = NULL, is.sorted = TRUE,
                        upstream = 2L, downstream = 2L) {
  if (!is.sorted) {
    grl <- sortPerGroup(grl)
    is.sorted <- TRUE
  }
  if (is.null(tx)) {
    tx <- grl
  }
  region <- windowPerGroup(stopSites(grl, TRUE, TRUE, is.sorted), tx,
                           upstream, downstream)
  return(region)
}

It is then possible to access any location relative to start/end of a "transcript", retaining the exon structure, : 

library(ORFik)
attach(loadNamespace("ORFik"))
attach(loadNamespace("data.table"))
gr.grl <- GRanges("1", IRanges(c(50, 100, 200), width = 25), "+")
grl <- split(gr.grl, seq_along(length(gr.grl)))
# tests
transformRegions(grl,upstream = 10, downstream = 40)# 40-74; 100-115
transformRegions(grl, fix = "end", upstream = 40, downstream = 27) # 109-124;200-251

It's useful for some purposes; 
Anyway, these range manipulation methods are very useful, thanks!

**Comment by Roleren** [comment] 2020-06-26 16:17
I made them because I was annoyed with how little GenomicRanges supported, hopefully one day I can remove it when it is supported in GenomicRanges, I will document the startRegion and windowPerGroup so that it points to extendLeaders etc. Will consider if I put this into ORFik or not. Closing this issue tomorrow unless you have something else you wanted to discuss.

**Comment by Miswi** [comment] 2020-06-26 18:50
Yes, I agree, GenomcRanges/GAlignments/GenomicFeatures - core packages look like abandoned project really. They should incorporate your functions if asked, maybe they didn't have time/resources to implement this (e.g. check behaviour of the promoters() function on  exonsBy() output, it really looks like a mistake).

I have more questions/issues, but I will just open new threads, this one is resolved, surely.

**Closed** 2020-06-29 11:41 UTC
Labels: enhancement
