### ISSUE TITLE
Interesting behavior of the findMapORFs function

### ISSUE THREAD

**Issue by hsinyenwu** [Roleren/ORFik#102] opened 2020-08-19 19:33 UTC
Hi Håkon,

I was wondering why the two slightly different DNA sequences give very different result. The first sequence gives an error and the second cases ran well. Could you please take a look?

Thanks,
Larry

Example 1
```
#Trying to find ATG start ORFs from DNA sequences.
library(ORFik)
x1 <- "1:1-199"
gr1 <- GRangesList(GRanges(x1,strand='+'))
names(gr1) <-"yfg1"

test_seqs <- "ATGCAGTCGAAGGGTAGGCTTCACAACTTCAGGTCGAGGAGCTTTTCGAGATCCAGACTCGCTATCGAAGGATCATAGCCAATAGCCATAGCTCTTTGTTACAGTCATCTCCGTCTCGAATTTCTTCTCTATTCATAGATTTCATTACCCTCGTGAAAAAATCGTCTCTTTTTTGTTTCCTAGTGTGTTCTCAATGAAA"
findMapORFs(gr1,test_seqs,longestORF=F,groupByTx=F,minimumLength = 0,startCodon = "ATG")

Result:
Error in if (g[x] != g[x - 1L]) { : missing value where TRUE/FALSE needed
```
 
Example 2: (slightly different sequences at the end than Example 1)
```
test_seqs <- "ATGCAGTCGAAGGGTAGGCTTCACAACTTCAGGTCGAGGAGCTTTTCGAGATCCAGACTCGCTATCGAAGGATCATAGCCAATAGCCATAGCTCTTTGTTACAGTCATCTCCGTCTCGAATTTCTTCTCTATTCATAGATTTCATTACCCTCGTGAAAAAATCGTCTCTTTTTTGTTTCCTAGTGTGTTCTCAATGTAA"
findMapORFs(gr1,test_seqs,longestORF=F,groupByTx=F,minimumLength = 0,startCodon = "ATG")```

Result:
GRangesList object of length 2:
  $yfg1_1
 GRanges object with 1 range and 1 metadata column:
   seqnames    ranges strand |       names
 <Rle> <IRanges>  <Rle> | <character>
   yfg1        1      1-78      + |      yfg1_1
   seqinfo: 1 sequence from an unspecified genome; no seqlengths
 
 $yfg1_2
GRanges object with 1 range and 1 metadata column:
   seqnames    ranges strand |       names
 <Rle> <IRanges>  <Rle> | <character>
   yfg1        1   194-199      + |      yfg1_2
   seqinfo: 1 sequence from an unspecified genome; no seqlengths
```

session_info()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ORFik_1.9.5                 GenomicAlignments_1.24.0    Rsamtools_2.4.0             Biostrings_2.56.0          
 [5] XVector_0.28.0              SummarizedExperiment_1.18.2 DelayedArray_0.14.1         matrixStats_0.56.0         
 [9] Biobase_2.48.0              GenomicRanges_1.40.0        GenomeInfoDb_1.24.2         IRanges_2.22.2             
[13] S4Vectors_0.26.1            BiocGenerics_0.34.0        

loaded via a namespace (and not attached):
 [1] httr_1.4.2             bit64_4.0.2            splines_4.0.2          R.utils_2.9.2          assertthat_0.2.1      
 [6] askpass_1.1            BiocFileCache_1.12.1   blob_1.2.1             GenomeInfoDbData_1.2.3 yaml_2.2.1            
[11] progress_1.2.2         pillar_1.4.6           RSQLite_2.2.0          lattice_0.20-41        glue_1.4.1            
[16] digest_0.6.25          RColorBrewer_1.1-2     colorspace_1.4-1       cowplot_1.0.0          R.oo_1.23.0           
[21] Matrix_1.2-18          plyr_1.8.6             DESeq2_1.28.1          XML_3.99-0.5           pkgconfig_2.0.3       
[26] biomaRt_2.44.1         genefilter_1.70.0      zlibbioc_1.34.0        purrr_0.3.4            xtable_1.8-4          
[31] scales_1.1.1           BiocParallel_1.22.0    tibble_3.0.3           openssl_1.4.2          annotate_1.66.0       
[36] generics_0.0.2         ggplot2_3.3.2          ellipsis_0.3.1         GenomicFeatures_1.40.1 survival_3.2-3        
[41] magrittr_1.5           crayon_1.3.4           memoise_1.1.0          R.methodsS3_1.8.0      GGally_2.0.0          
[46] data.table_1.13.0      tools_4.0.2            prettyunits_1.1.1      hms_0.5.3              lifecycle_0.2.0       
[51] stringr_1.4.0          munsell_0.5.0          locfit_1.5-9.4         AnnotationDbi_1.50.3   compiler_4.0.2        
[56] rlang_0.4.7            grid_4.0.2             RCurl_1.98-1.2         rstudioapi_0.11        rappdirs_0.3.1        
[61] bitops_1.0-6           gtable_0.3.0           reshape_0.8.8          DBI_1.1.0              curl_4.3              
[66] R6_2.4.1               gridExtra_2.3          dplyr_1.0.1            rtracklayer_1.48.0     bit_4.0.4             
[71] biomartr_0.9.2         stringi_1.4.6          Rcpp_1.0.5             vctrs_0.3.2            geneplotter_1.66.0    
[76] dbplyr_1.4.4           tidyselect_1.1.0

**Comment by Miswi** [comment] 2020-08-20 11:32
Hey, 
I was digging in findMapORFs recently, for other reasons, but the reason for this bug is this loop in makeExonRanks:
        for (x in seq.int(2L, length(g))) {
            if (g[x] != g[x - 1L]) {
                if (oldNames[g[x]] == oldNames[g[x] - 1L]) {
                  inds[x] <- inds[x - 1L] + 1L
                }
            }
if there is only one orf found, then the x iterates over c(2,1), and thus we hit g[1] != g[0], which gives the error.
the shortest reproducible example of this error is:

x1 <- GRanges("1:1-6:+")
x2 <- GRanges("1:1-9:+")

gr1 <- GRangesList(x1,x2)
names(gr1) <-c("yfg1","yfg2")
test_seqs <- c("ATGTAA","ATGATGTAA")
findMapORFs(gr1[1],test_seqs[1],longestORF=F,groupByTx=F,minimumLength = 0,startCodon = "ATG")
findMapORFs(gr1[2],test_seqs[2],longestORF=F,groupByTx=F,minimumLength = 0,startCodon = "ATG")

Hope it helps.

**Comment by Roleren** [comment] 2020-08-20 11:33
This was a bug for running single sequence with 1 ORF, with a corner case sequence. 

Thanks, this is now fixed in newest version.

devtools::install_github("Roleren/ORFik")
Will be updated in devel branch in a few days too.

**Comment by Miswi** [comment] 2020-08-20 11:35
Ah, cool, before you close the issue, I had a question about underscores in gene names - with findMapORFs these were stripped 
(for example gene_1 would become gene, and newly found ORFs would have numbering gene_1, gene_2 etc), but I see that it is changed now, because I cannot reproduce, is that correct?

**Comment by Roleren** [comment] 2020-08-20 11:43
Yes, I fixed that a few months ago I think.

 ```
library(ORFik)
 x1 <- "1:1-199"
 gr1 <- GRangesList(GRanges(x1,strand='+'))
 names(gr1) <- "gene_1"
 
 test_seqs <- "ATGCAGTCGAAGGGTAGGCTTCACAACTTCAGGTCGAGGAGCTTTTCGAGATCCAGACTCGCTATCGAAGGATCATAGCCAATAGCCATAGCTCTTTGTTACAGTCATCTCCGTCTCGAATTTCTTCTCTATTCATAGATTTCATTACCCTCGTGAAAAAATCGTCTCTTTTTTGTTTCCTAGTGTGTTCTCAATGAAA"
 findMapORFs(gr1,test_seqs,longestORF=F,groupByTx=F,minimumLength = 0,startCodon = "ATG")
```
gives:
```
GRangesList object of length 1:
$gene_1_1
GRanges object with 1 range and 1 metadata column:
         seqnames    ranges strand |       names
            <Rle> <IRanges>  <Rle> | <character>
  gene_1        1      1-78      + |    gene_1_1
  -------
  seqinfo: 1 sequence from an unspecified genome; no seqlengths

```

**Comment by Miswi** [comment] 2020-08-20 11:47
Yeah, I ended up removing underscores from gene names while reading in the data and didn't notice the change, that's handy, thanks!

**Closed** 2020-08-20 11:51 UTC
Labels: bug
